### ISSUE TITLE
Need a simple way to add partners to the campaign pages

### ISSUE THREAD

**Issue by rossbruniges** [mozilla/make.mozilla.org#20]
The summer (and future) campaign will have partners that we'll want to promote.

Would rather not need to do an deploy to add these so thinking something along the lines of a dead-simple app that allows people to do so would be sweet.

Required fields:

Name
URL
Image (upload to a path on the server)
Featured (boolean value - displays partners on the summer-campaign page)
Campaign - foreign key to the campaign model.

**Comment by fidothe** [comment]
Image uploads fixed in 8f910725f27dee686edf68b474a3decb96222134
