### ISSUE TITLE
BrowserID sign-up flow required

### ISSUE THREAD

**Issue by rossbruniges** [mozilla/make.mozilla.org#3]
User needs to be logged in to access /events/new, /events/create (anything else?)

On initial log-in redirected to a small profile creation form - where they can provide us with a display name (definately) and brief description (possibly).

Site avatar will come from gravatar 

This is a fairly standard user flow process and code should be able to be cribbed from firefox-flicks or ignite

**Comment by fidothe** [comment]
fixed in 4e2cf621f45effc519cc2a

**Comment by fidothe** [comment]
NB: we're not doing profile / gravatar at the moment since no-one sees a user's profile (not even them...)

**Comment by rossbruniges** [comment]
Did a quick tidy up job on the browserID sign-up form in commit https://github.com/rossbruniges/make.mozilla.org/commit/daf9c92f4e08d40626fef1f0e11b977d391a4dbe
