### ISSUE TITLE
Add in a 'teach' tab to the global nav

### ISSUE THREAD

**Issue by rossbruniges** [mozilla/make.mozilla.org#99]
- URL should be ''/teach/"
- make sure that the tab highlights on the correct pages (be aware of the two potential URL structures
- nav order should be: Projects | Tools | Events | Teach | About

**Comment by OpenMatt** [comment]
I'm cool with that. But Brett needs to sign off.

**Comment by rossbruniges** [comment]
He did in IRC

**Comment by OpenMatt** [comment]
Awesome. I love it.
